//
//  DescriptionText.swift
//  videoPlayerChallenge
//
//  Created by M. A. Alim Mukul on 12.09.22.
//

import Foundation

var description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit duis tristique sollicitudin nibh. Euismod in pellentesque massa placerat duis ultricies lacus sed turpis. Feugiat vivamus at augue eget arcu dictum varius. Nunc non blandit massa enim nec dui nunc. Ipsum suspendisse ultrices gravida dictum fusce ut. Egestas diam in arcu cursus euismod quis. Id semper risus in hendrerit. Aliquam sem et tortor consequat id. Feugiat pretium nibh ipsum consequat. Congue eu consequat ac felis donec et. Arcu odio ut sem nulla. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Sem et tortor consequat id porta nibh venenatis cras sed. Volutpat lacus laoreet non curabitur gravida arcu ac. Ac tincidunt vitae semper quis lectus nulla at volutpat. Dui vivamus arcu felis bibendum ut. Risus in hendrerit gravida rutrum quisque non tellus orci. Nulla pharetra diam sit amet. Accumsan tortor posuere ac ut consequat semper viverra. Massa massa ultricies mi quis hendrerit dolor. In pellentesque massa placerat duis. Eget arcu dictum varius duis at consectetur lorem donec massa. Curabitur gravida arcu ac tortor dignissim convallis aenean. Congue mauris rhoncus aenean vel. Massa ultricies mi quis hendrerit dolor magna eget. Sodales neque sodales ut etiam sit amet nisl. Et ligula ullamcorper malesuada proin libero nunc consequat. Semper quis lectus nulla at volutpat diam ut. Non odio euismod lacinia at quis. Nulla aliquet porttitor lacus luctus accumsan tortor. Gravida cum sociis natoque penatibus et. Risus at ultrices mi tempus imperdiet nulla. Enim tortor at auctor urna. Quam lacus suspendisse faucibus interdum posuere lorem. Fames ac turpis egestas maecenas. Arcu ac tortor dignissim convallis aenean et tortor at risus. Tellus elementum sagittis vitae et leo duis ut. Dapibus ultrices in iaculis nunc sed. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Dui sapien eget mi proin sed libero enim. Id eu nisl nunc mi ipsum faucibus vitae. Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing."
